### ISSUE TITLE
Cannot find module 'atom-message-panel' when trying to compile

### ISSUE THREAD

**Issue by nharrand** [SINTEF-9012/language-atomthingml#1]
### Steps to reproduce

1. Open a ThingML file
2. Compile to Arduino

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [language-thingml](https://github.com/SINTEF-9012/language-atomthingml) package 0.1.0

### Stack Trace

Failed to activate the language-thingml package

```
At Cannot find module 'atom-message-panel'

Error: Cannot find module 'atom-message-panel'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/opt/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/opt/atom/resources/app/src/module-cache.js:354:1)
    at Module.require (opt/atom/resources/app/static/index.js:40:43)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:1)
    at /packages/language-atomthingml/lib/main.js:6:53)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (opt/atom/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/opt/atom/resources/app/static/<embedded>:73:1)
    at Package.module.exports.Package.requireMainModule (/opt/atom/resources/app/src/package.js:887:1)
    at Package.module.exports.Package.activateNow (/opt/atom/resources/app/src/package.js:242:1)
    at /opt/atom/resources/app/src/package.js:968:1
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:246:1)
    at CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/atom/resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/opt/atom/resources/app/src/atom-environment.js:1306:1)
    at EventEmitter.outerCallback (/opt/atom/resources/app/src/application-delegate.js:347:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  2x -4:13.3.0 editor:newline (input.hidden-input)
  3x -4:11.7.0 core:backspace (input.hidden-input)
  2x -4:09.6.0 editor:newline (input.hidden-input)
  3x -4:08.8.0 core:backspace (input.hidden-input)
  6x -4:02.9.0 editor:newline (input.hidden-input)
  7x -3:54 core:backspace (input.hidden-input)
     -0:50.5.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:38.6.0 language-thingml:compile-arduino (div.line)
```

### Non-Core Packages

```
language-thingml 0.1.0 
```

**Comment by brice-morin** [comment]
first you need to `npm install`. The package is not yet released as a atom package, so you have to install manually

Then, it will be other issues on Linux, but @barais has a fix he will commit.

**Comment by nharrand** [comment]
Cool!

**Comment by barais** [comment]
Don't be afraid, there will be other bugs ;)

I send you the patch for linux
